eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/ # URL of the Eureka server
    register-with-eureka: true # Enable client registration
    fetch-registry: true       # Fetch registry from Eureka server
  instance:
    prefer-ip-address: true    # Use IP address for registration instead of hostname
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_security_practice
    username: root
    password: Lifestain@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
